### PR TITLE
Add unit tests for TextParser

### PR DESCRIPTION
**Pull request by mwilbz**
# Overview

Starting out by adding unit tests for one module. Let me know if you have any suggestions so I can do better for the remaining modules =) In general I'm aiming to mock out any parsing/tokenization behavior to keep unit tests fast and stable even if there are changes in the `spacy` implementation.

# Changes

- Adds unit tests for the functions in `textParser.py`.
- Adds test utilities in `convokit/tests/utils.py` for unit testing using `spacy` Doc's
- Moves the `tests/` directory into the `convokit` module. See Discussion below

# Testing

All new and existing tests run successfully in CI

# Discussion

Moving `tests/` into the `convokit` module is a significant change to the project structure, but I think it's a best practice that allows us to use [absolute imports in tests](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/compare/master...mwilbz:text-parser-tests?expand=1#diff-e5414bd12f72dcd3ba956162cce5600dR4). I also benefitted from `spacy` structuring their project this way as I could [utilize their test utilities](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/compare/master...mwilbz:text-parser-tests?expand=1#diff-b0b0fc4ebe4f185a5e1e945505369187R1).

### CODE REVIEW

**Comment by calebchiam** [comment]
Hi @mwilbz, thanks for the tests! I think the reorganization makes sense. Regarding the TextParser unit tests, I think they make sense though the focus should be more on the transformer's core functions. For example, rather than call TextParser's static (helper) methods, the tests should initialize a TextParser object and run TextParser.transform() and TextParser.transform_utterance() on a test corpus and test utterance respectively. (See [this demo](https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/examples/text-processing/text_preprocessing_demo.ipynb) for an example.)

**Comment by mwilbz** [comment]
Thanks @calebchiam , I've updated the tests for `process_text` to now call `transform` on a `Corpus`! Let me know what you think.

Also, I've noticed the CI I set up isn't running for this PR. I wonder if Github Actions are turned off on a repository or organization level? Can you check the repository settings at Settings -> Actions to see if we need to enable them?

**Comment by calebchiam** [comment]
Thanks! I think we're nearly good to go on this PR. Could I check why `fake_spacy_nlp` and `FakeSentenceTokenizer` are used here? Is this to speed up the test's computation time? Apart from that, one small change to make is `corpus.utterances.values()` -> `corpus.iter_utterances()`, since `utterances` is not intended to be a public field of Corpus.

Regarding CI, here's my view of the Actions tab. There doesn't seem to be a toggle-able setting. Perhaps the GitHub Actions configuration needs to be specified to run on pull requests?

Screenshot 2020-05-31 at 9 02 09 AM

**Comment by mwilbz** [comment]
Aha! Thanks, it was a little confusing that `.utterances` wasn't a list of `Utterance`s.

- CI: Sorry, not the Actions tab on the top level, but under the repo's Settings. That should be another tab which has an "Actions" section on the side bar. It seems you can't see Settings to the right of Insights so perhaps you're not an admin on the repo?
- Fake objects: Yeah, exactly. Fake objects result in faster tests, and tests that don't break when `spacy` parsers are modified. This is part of the philosophy of [unit testing](https://circleci.com/blog/how-to-test-software-part-i-mocking-stubbing-and-contract-testing/) which are almost a necessity on large codebases. That said, this isn't a large codebase (yet) so it's possible I'm doing overkill here, but it's just a best practice I'm used to at this point. The `spacy` library also takes this approach [as a contributor describes here](https://stackoverflow.com/questions/56728218/how-to-mock-spacy-models-doc-objects-for-unit-tests).

**Comment by calebchiam** [comment]
Ah, I see. I'll look into configuring the settings but I've merged the PR for now. Thanks!

**Comment by mwilbz** [comment]
Thanks Caleb!

**Pull request merged**
